#include "blocks.h"

std::unordered_map<std::string, blocks::Block> blocks::blockMap = {
    {"minecraft:stone", Block::Stone},
    {"minecraft:grass", Block::Grass},
    {"minecraft:dirt", Block::Dirt},
    {"minecraft:cobblestone", Block::Cobblestone},
    {"minecraft:planks", Block::Planks},
    {"minecraft:bedrock", Block::Bedrock},
    {"minecraft:sand", Block::Sand},
    {"minecraft:gravel", Block::Gravel},
    {"minecraft:log", Block::Log},
    {"minecraft:sponge", Block::Sponge},
    {"minecraft:glass", Block::Glass},
    {"minecraft:sandstone", Block::Sandstone},
    {"minecraft:wool", Block::Wool},
    {"minecraft:brick_block", Block::BrickBlock},
    {"minecraft:obsidian", Block::Obsidian},
    {"minecraft:stained_glass", Block::StainedGlass},
    {"minecraft:end_stone", Block::EndStone},
    {"minecraft:stained_hardened_clay", Block::StainedHardenedClay},
    {"minecraft:log2", Block::Log2},
    {"minecraft:red_sandstone", Block::RedSandstone},
    {"minecraft:quartz_block", Block::QuartzBlock},
    {"minecraft:stonebrick", Block::StoneBrick},
    {"minecraft:clay", Block::Clay},
    {"minecraft:snow", Block::SnowBlock},
    {"minecraft:ice", Block::Ice},
    {"minecraft:packed_ice", Block::PackedIce},
    {"minecraft:coal_block", Block::CoalBlock},
    {"minecraft:iron_block", Block::IronBlock},
    {"minecraft:gold_block", Block::GoldBlock},
    {"minecraft:diamond_block", Block::DiamondBlock},
    {"minecraft:emerald_block", Block::EmeraldBlock},
    {"minecraft:lapis_block", Block::LapisBlock},
    {"minecraft:redstone_block", Block::RedstoneBlock},
    {"minecraft:nether_brick", Block::NetherBrick},
    {"minecraft:glowstone", Block::Glowstone},
    {"minecraft:prismarine", Block::Prismarine},
    {"minecraft:sea_lantern", Block::SeaLantern},
    {"minecraft:hay_block", Block::HayBlock},
    {"minecraft:hardened_clay", Block::HardenedClay},
    {"minecraft:melon_block", Block::MelonBlock},
    {"minecraft:pumpkin", Block::Pumpkin},
    {"minecraft:netherrack", Block::Netherrack},
    {"minecraft:soul_sand", Block::SoulSand},
    {"minecraft:mycelium", Block::Mycelium},
    {"minecraft:bookshelf", Block::Bookshelf},
    {"minecraft:mossy_cobblestone", Block::MossyCobblestone},
    {"minecraft:chiseled_sandstone", Block::ChiseledSandstone},
    {"minecraft:smooth_sandstone", Block::SmoothSandstone},
    {"minecraft:chiseled_red_sandstone", Block::ChiseledRedSandstone},
    {"minecraft:smooth_red_sandstone", Block::SmoothRedSandstone},
    {"minecraft:coal_ore", Block::CoalOre},
    {"minecraft:iron_ore", Block::IronOre},
    {"minecraft:gold_ore", Block::GoldOre},
    {"minecraft:diamond_ore", Block::DiamondOre},
    {"minecraft:emerald_ore", Block::EmeraldOre},
    {"minecraft:lapis_ore", Block::LapisOre},
    {"minecraft:redstone_ore", Block::RedstoneOre}
};

bool blocks::isUsingBlocks(JNIEnv* env) {
	std::string item = player::getHeldItem(env);

    return blockMap.find(item.c_str()) != blockMap.end();
}